### ISSUE TITLE
download_stf_dockets.R

### ISSUE THREAD

**Issue by Lucasfm108** [jjesusfilho/stf#1]
Boa tarde, 

Gentileza conferir a função download_stf_dockets.R. 
Tentei rodá-la, mas, aparentemente, está com algum erro. Ela cria as quatro pastas (andamentos, detalhes, informações e partes), porém, somente na de "detalhes" é criado o arquivo html.

Desde já, agradeço e parabenizo pelo pacote.

Abraços, Lucas.

**Comment by jjesusfilho** [comment]
Oi Lucas,

Creio que isso já tenha sido corrigido. Pode testar para ver se está funcionando?
